name: Deploy Edge Functions

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # Skip the database linking step since we only need to deploy the function
      # - name: Link to Supabase Project
      #   run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} -p ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Verify deno.json exists
        run: |
          ls -la supabase/functions/users-api/deno.json
          cat supabase/functions/users-api/deno.json
          echo "Ensuring deno.json is properly set up"

      - name: Flatten and deploy Edge Functions
        run: |
          # Create flattened directory structure while maintaining the original path
          chmod +x ./scripts/flatten-directory.sh
          ./scripts/flatten-directory.sh
          
          # Deploy from the flattened structure at the original path
          cd supabase/functions/users-api
          ls -la
          
          # Deploy using the flattened files
          supabase functions deploy users-api --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --no-verify-jwt --debug
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}