name: Deploy Edge Functions

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Setup Deno (Compatible with Supabase Edge Runtime)
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.45.2

      - name: Prepare deployment (clean cache)
        run: |
          rm -f supabase/functions/users-api/deno.lock
          rm -rf ~/.cache/deno
          rm -rf ~/.cache/supabase
          rm -rf .supabase

      - name: Deploy Edge Functions
        run: |
          supabase functions deploy users-api --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}